// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_jvAcbAiksrQ61NH7Xn9LLFuv296P4c',
    appId: '1:645481279664:web:6d54697d2b7db11a12cb75',
    messagingSenderId: '645481279664',
    projectId: 'fir-analytics-7e2e6',
    authDomain: 'fir-analytics-7e2e6.firebaseapp.com',
    storageBucket: 'fir-analytics-7e2e6.appspot.com',
    measurementId: 'G-WTZTXD26EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCod9fOC8ZSMsFeXEfQrYCnWe_um0-ABoo',
    appId: '1:645481279664:android:616b4f61a2863a6d12cb75',
    messagingSenderId: '645481279664',
    projectId: 'fir-analytics-7e2e6',
    storageBucket: 'fir-analytics-7e2e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQrXjKtC-5rskPk-5H9RPfaRodKvSnCro',
    appId: '1:645481279664:ios:575ae76350e976e812cb75',
    messagingSenderId: '645481279664',
    projectId: 'fir-analytics-7e2e6',
    storageBucket: 'fir-analytics-7e2e6.appspot.com',
    iosBundleId: 'com.example.firebaseAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQrXjKtC-5rskPk-5H9RPfaRodKvSnCro',
    appId: '1:645481279664:ios:575ae76350e976e812cb75',
    messagingSenderId: '645481279664',
    projectId: 'fir-analytics-7e2e6',
    storageBucket: 'fir-analytics-7e2e6.appspot.com',
    iosBundleId: 'com.example.firebaseAnalytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_jvAcbAiksrQ61NH7Xn9LLFuv296P4c',
    appId: '1:645481279664:web:fdbd5bc2f80fbb3012cb75',
    messagingSenderId: '645481279664',
    projectId: 'fir-analytics-7e2e6',
    authDomain: 'fir-analytics-7e2e6.firebaseapp.com',
    storageBucket: 'fir-analytics-7e2e6.appspot.com',
    measurementId: 'G-F29T0YP89T',
  );
}
